[package]
description = "An attribute macro to easily time a function."
edition = "2021"
name = "timed"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = { version = "2.0.58", features = ["full", "printing"] }
proc-macro2 = "1.0.79"
